### ISSUE TITLE
[Feature]: Dockerfile addition for easily setting up project locally.

### ISSUE THREAD

**Issue by SahilSinghTomar** [akshat-OwO/syllabusx-client#104] opened 2024-08-23 05:12 UTC
### What feature do you want?

A feature request!

**Comment by SahilSinghTomar** [comment] 2024-08-27 04:03
I can solve this issue. can you please assign it to me

**Comment by akshat-OwO** [comment] 2024-08-27 04:09
go ahead

**Comment by akshat-OwO** [comment] 2024-09-03 16:28
@SahilSinghTomar any progress till now?

**Comment by SahilSinghTomar** [comment] 2024-09-03 16:33
@akshat-OwO I am sorry. I tried to solve it but didn't able to figure it out.

**Comment by akshat-OwO** [comment] 2024-09-03 16:41
no worries

**Comment by Lakshay-Jain-1** [comment] 2024-09-22 11:42
I can solve this issue. Please assign it to me. I was learning about Docker, it couldn't have come at a better time.

**Comment by akshat-OwO** [comment] 2024-09-22 12:15
have fun

**Comment by Lakshay-Jain-1** [comment] 2024-09-23 08:20
Update: i have uploaded the docker image to docker hub by this name lakshayjain1/syllabusx 
When you run this image you have to do port mapping by the way , here is the command for your convenience
 docker run -it -p 3000:3000 lakshayjain1/syllabusx

future task 
---i have to change image name , 
---image size is 2.8 gb , i will try to decrease this image size
---add you as a collaborator in docker hub ,so that you can change image
---to push my code to your repo , it is my first time contributing to someone else repo


DO YOU WANT ME to change readme file so that i can add commands and make me as a contributor 😊 ??
 
 AND i will do rest of my tasks after my mid  sem is over if it is okay with you !!!

**Comment by akshat-OwO** [comment] 2024-09-26 10:32
hey @Lakshay-Jain-1,
imo creating a docker image public as your namespace for an opensource project should not be the right thing to do. Instead you should create `Dockerfile` and `docker-compose.yml` files, which then can be used.
And you don't need to be worried about the size of image as it will be only used for developing purposes for devs who have not setup node in their local machine or have different node version.
Keep in mind the volume used should allow hot reloading as well.

You are allowed to change readme and can continue after mid sems

**Comment by akshat-OwO** [comment] 2024-10-28 15:36
@Lakshay-Jain-1 any progress on this it's been a very long time

**Comment by Lakshay-Jain-1** [comment] 2024-10-30 21:49
@akshat-OwO
sorry , I forgot to update you on my progress with adding hot reloading to the Dockerized Next.js project.
 Unfortunately, it’s not working at all, and I’ve tried several solutions. I think the issue lies in how I'm mapping the current directory to the container’s working directory.

If you have experience with Docker, could you help me identify where I might be going wrong?

#### Dockerfile

```dockerfile
FROM node:20


RUN npm install -g nodemon


WORKDIR /app


COPY package*.json pnpm-lock.yaml* ./


RUN npm install -g pnpm


RUN pnpm install

COPY . .

EXPOSE 3000


CMD ["nodemon", "--watch", ".", "--exec", "pnpm run dev"]
```

#### Docker Compose File

```yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app                    # Map the entire codebase with /app
      - /app/node_modules          
      - /app/.next                
    command: ["pnpm", "run", "dev"]
```

**Comment by akshat-OwO** [comment] 2024-10-31 09:51
nodemon is not required, install pnpm copy package.json and run pnpm install. You can also copy pnpm lock file and install using --frozen-lockfile flag in pnpm install cmd. Copy everthing expose 3000 and run pnpm run dev

in compose file:
you can remove environment and command key-value, and in volumes, put only `.:/app` remove others

try this

**Comment by Lakshay-Jain-1** [comment] 2024-10-31 17:18
tried your solution  but got an error , and i resolved that error still it is not supporting hot reloading , i scrape through youtube and google that someone has done this but tried their solution still it is not working 


dockerFile
```docker
FROM node:20
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
EXPOSE 3000
CMD ["pnpm", "run", "dev"]
```

docker compose file
```docker
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
      
```
getting this error 
```docker
PS C:\Users\laksh\Desktop\syllabusx-client-main> docker compose up
[+] Running 1/1
 ✔ Container syllabusx-client-main-web-1  Recreated                                                                                                                        0.1s 
Attaching to web-1
web-1  |
web-1  | > syllabusx-client@4.8.0 dev /app
web-1  | > next dev                                                                                                                                                             
web-1  |                                                                                                                                                                        
web-1  | sh: 1: next: not found                                                                                                                                                 
web-1  |  ELIFECYCLE  Command failed.                                                                                                                                           
web-1 exited with code 1
```      

how i resolved this error was by adding 2 more volume in docker compose file  
```docker
      - /app/node_modules         
      - /app/.next      
```

### I am using windows  . I guess the issue is that docker is struggling with the file system of windows

**Comment by akshat-OwO** [comment] 2024-10-31 17:43
windows shouldn't be the problem here. Overall weird issue but if this works you can create PR, also update the contribution list and little documentation for setup with docker in readme

**Comment by Lakshay-Jain-1** [comment] 2024-11-06 21:30
Finally the issue has been resolved , in docker for hot reloading there is a feature called develop , will create PR later
and when i was using volumes for hot reloading file was getting updated it was not rendering , you have to do docker compose up -d every time when there are any changes 

https://github.com/user-attachments/assets/5963dc39-d05f-4fa8-a22d-0ce5e2bcaa30

**Closed** 2024-11-10 04:00 UTC
Labels: enhancement, good first issue
